# Generated by Django 4.2.11 on 2024-04-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendemailtask",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_logs",
                to="core.contact",
            ),
        ),
    ]
