# Generated by Django 4.2.13 on 2024-06-18 11:51

import common.array_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_unacent"),
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="bcc_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Add all contacts from this group in the Bcc for all sent emails.",
                limit_choices_to=models.Q(("contacts", None), _negated=True),
                related_name="sent_emails_bcc",
                to="core.contactgroup",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="bcc_recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text="Add these recipients in the Bcc for all sent emails.",
                limit_choices_to=models.Q(("emails", []), _negated=True),
                related_name="sent_emails_bcc",
                to="core.contact",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="cc_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Add all contacts from this group in the Cc for all sent emails.",
                limit_choices_to=models.Q(("contacts", None), _negated=True),
                related_name="sent_emails_cc",
                to="core.contactgroup",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="cc_recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text="Add these recipients in the Cc for all sent emails.",
                limit_choices_to=models.Q(("emails", []), _negated=True),
                related_name="sent_emails_cc",
                to="core.contact",
            ),
        ),
        migrations.AddField(
            model_name="sendemailtask",
            name="bcc_contacts",
            field=models.ManyToManyField(
                related_name="email_logs_bcc", to="core.contact"
            ),
        ),
        migrations.AddField(
            model_name="sendemailtask",
            name="cc_contacts",
            field=models.ManyToManyField(
                related_name="email_logs_cc", to="core.contact"
            ),
        ),
        migrations.AddField(
            model_name="sendemailtask",
            name="email_bcc",
            field=common.array_field.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                editable=False,
                help_text="List of email addresses this email was sent to in Bcc.",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="sendemailtask",
            name="email_cc",
            field=common.array_field.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                editable=False,
                help_text="List of email addresses this email was sent to in Cc.",
                null=True,
                size=None,
            ),
        ),
    ]
