# Generated by Django 4.2.11 on 2024-04-11 07:41

import common.array_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendemailtask",
            name="email_cc",
            field=common.array_field.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                editable=False,
                help_text="List of email addresses this email was sent to in CC.",
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="sendemailtask",
            name="email_to",
            field=common.array_field.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                editable=False,
                help_text="List of email addresses this email was sent to.",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Send the email to all contacts in these selected groups.",
                to="core.contactgroup",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text="Send the email to all the selected contacts.",
                to="core.contact",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="subject",
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="description",
            field=models.TextField(
                help_text="A short description for the template, displayed in the list when choosing a template for an email."
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="title",
            field=models.CharField(
                help_text="Name of the template, used to identify the template when selecting it.",
                max_length=250,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="sendemailtask",
            name="sent_email",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Complete copy of the sent email.",
                null=True,
            ),
        ),
    ]
