# Generated by Django 5.2.1 on 2025-05-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0002_email_bcc_groups_email_bcc_recipients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailattachment",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name to use for the attachment, defaults to the uploaded filename if not specified.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sendemailtask",
            name="sent_email",
            field=models.TextField(
                blank=True, default="", help_text="Complete copy of the sent email."
            ),
        ),
    ]
