# Generated by Django 5.2.1 on 2025-05-27 19:41

import django.core.files.storage
import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_contact_organization_and_more"),
        ("emails", "0003_alter_emailattachment_name_and_more"),
        ("events", "0006_eventinvitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationEmail",
            fields=[],
            options={
                "verbose_name": "Invitation Email",
                "verbose_name_plural": "Invitation Emails",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("emails.email",),
        ),
        migrations.AddField(
            model_name="email",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("EVENT INVITE", "Event Invite"),
                    ("EVENT_NOTIFICATION", "Event Notification"),
                ],
                default="EVENT_NOTIFICATION",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="event_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Send the email to all participants of the events in this event group.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_emails",
                to="events.eventgroup",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="organization_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Send the email to primary contacts of these organization types.",
                related_name="sent_emails",
                to="core.organizationtype",
            ),
        ),
        migrations.AddField(
            model_name="sendemailtask",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_tasks",
                to="events.eventinvitation",
            ),
        ),
        migrations.AddField(
            model_name="sendemailtask",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_tasks",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="sendemailtask",
            name="to_contacts",
            field=models.ManyToManyField(
                related_name="email_logs_to", to="core.contact"
            ),
        ),
        migrations.AlterField(
            model_name="emailattachment",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/protected_media/",
                    location=pathlib.PurePosixPath(
                        "/Users/sorinstelian/edw/contactdb/.fs/protected_media"
                    ),
                ),
                upload_to="email_files/",
            ),
        ),
    ]
