# Generated by Django 5.2.1 on 2025-05-26 09:57

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0003_alter_emailattachment_name_and_more"),
        ("events", "0006_eventinvitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationEmail",
            fields=[],
            options={
                "verbose_name": "Invitation Email",
                "verbose_name_plural": "Invitation Emails",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("emails.email",),
        ),
        migrations.AddField(
            model_name="email",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("EVENT INVITE", "Event Invite"),
                    ("EVENT_NOTIFICATION", "Event Notification"),
                ],
                default="EVENT_NOTIFICATION",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="organization_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Send the email to primary contacts of these organization types.",
                related_name="sent_emails",
                to="core.organizationtype",
            ),
        ),
        migrations.AddField(
            model_name="sendemailtask",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_tasks",
                to="events.eventinvitation",
            ),
        ),
        migrations.AddField(
            model_name="sendemailtask",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_tasks",
                to="core.organization",
            ),
        ),
    ]
