# Generated by Django 5.2.1 on 2025-05-27 10:40

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_invitationemail_email_email_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemailtask',
            name='to_contacts',
            field=models.ManyToManyField(related_name='email_logs_to', to='core.contact'),
        ),
    ]
