# Generated by Django 5.2.1 on 2025-05-29 16:20

from django.db import migrations, models

import common.model


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0004_invitationemail_email_email_type_email_event_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailattachment",
            name="file",
            field=models.FileField(
                storage=common.model.get_protected_storage, upload_to="email_files/"
            ),
        ),
    ]
