# Generated by Django 5.2.1 on 2025-05-27 15:49


import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0005_sendemailtask_to_contacts_alter_emailattachment_file"),
        ("events", "0006_eventinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="event_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Send the email to all participants of the events in this event group.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_emails",
                to="events.eventgroup",
            ),
        ),
    ]
