# Generated by Django 5.2.1 on 2025-06-04 12:05

import emails.placeholders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0005_alter_emailattachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="subject",
            field=models.CharField(
                max_length=900, validators=[emails.placeholders.validate_placeholders]
            ),
        ),
    ]
