# Generated by Django 5.2.1 on 2025-06-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0005_alter_emailattachment_file"),
        ("events", "0008_registration_created_at_registration_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="events",
            field=models.ManyToManyField(
                blank=True,
                help_text="Send the email to all participants of these selected events.",
                related_name="sent_emails",
                to="events.event",
            ),
        ),
    ]
