# Generated by Django 5.2.1 on 2025-06-06 10:19

from django.db import migrations, models

import emails.placeholders


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0006_alter_email_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="subject",
            field=models.CharField(
                max_length=900, validators=[emails.placeholders.validate_placeholders]
            ),
        ),
    ]
