# Generated by Django 5.2.1 on 2025-06-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0007_alter_email_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="is_reminder",
            field=models.BooleanField(
                default=False,
                help_text="Is this a reminder email for a previously sent invitation",
            ),
        ),
    ]
