# Generated by Django 5.2.1 on 2025-06-13 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0007_alter_email_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="is_reminder",
            field=models.BooleanField(
                default=False,
                help_text="Is this a reminder email for a previously sent invitation, for organizations that have not registered any contacts yet. This changes email behaviour: only sends mails to 'unregistered' orgs.",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="original_email",
            field=models.ForeignKey(
                blank=True,
                help_text="The original invitation email this is a reminder for.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminder_emails",
                to="emails.email",
            ),
        ),
    ]
