# Generated by Django 5.2.1 on 2025-07-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_contact_designation_and_more"),
        ("emails", "0009_email_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="organizations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Send the email to primary contacts of these organizations.",
                null=True,
                related_name="sent_emails",
                to="core.organization",
            ),
        ),
    ]
