# Generated by Django 5.2.1 on 2025-07-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0010_email_organizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="is_draft",
            field=models.BooleanField(
                default=False,
                help_text="Is this email saved as draft and not yet sent out.",
            ),
        ),
    ]
