# Generated by Django 5.2.1 on 2025-08-27 12:14

from django.db import migrations, models


def migrate_org_types(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    InvitationEmail = apps.get_model("emails", "InvitationEmail")
    OrganizationTypeNew = apps.get_model("core", "OrganizationTypeNew")

    mapping = {}
    for org_type in OrganizationTypeNew.objects.using(db_alias).all():
        mapping[org_type.acronym] = org_type

    for email in (
        InvitationEmail.objects.using(db_alias)
        .filter(organization_types__isnull=False)
        .all()
    ):
        old_org_types = email.organization_types.all()
        email.organization_types_new.set(
            [mapping[org_type.acronym] for org_type in old_org_types]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_organizationtypenew_and_more"),
        ("emails", "0010_email_organizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="organization_types_new",
            field=models.ManyToManyField(
                blank=True,
                help_text="Send the email to primary contacts of these organization types.",
                related_name="sent_emails_new",
                to="core.organizationtypenew",
            ),
        ),
        migrations.RunPython(migrate_org_types, migrations.RunPython.noop),
    ]
