# Generated by Django 5.2.1 on 2025-08-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0011_email_organization_types_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="organization_types",
        ),
        migrations.RenameField(
            model_name="email",
            old_name="organization_types_new",
            new_name="organization_types",
        ),
        migrations.AlterField(
            model_name="email",
            name="organization_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Send the email to primary contacts of these organization types.",
                related_name="sent_emails",
                to="core.organizationtypenew",
            ),
        ),
    ]
