# Generated by Django 5.2.7 on 2025-11-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0012_auto_20250827_1225"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="is_draft",
            field=models.BooleanField(
                default=False,
                help_text="Is this email saved as draft and not yet sent out.",
            ),
        ),
    ]
