# Generated by Django 4.2.13 on 2024-06-21 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loadparticipantsfromkronostask",
            name="contacts_nr",
            field=models.PositiveIntegerField(
                default=0, editable=False, help_text="Number of newly created contacts."
            ),
        ),
        migrations.AlterField(
            model_name="loadparticipantsfromkronostask",
            name="event",
            field=models.ForeignKey(
                help_text="Event to import participants for in this task.",
                limit_choices_to=models.Q(("event_id__isnull", False)),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_tasks",
                to="events.event",
            ),
        ),
    ]
