# Generated by Django 5.2.1 on 2025-05-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_loadparticipantsfromkronostask_contacts_nr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="priority_pass_code",
            field=models.CharField(blank=True, default="", max_length=150),
            preserve_default=False,
        ),
    ]
