# Generated by Django 5.2.1 on 2025-05-15 08:22

from django.db import migrations, models

import common.citext


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_registration_priority_pass_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", common.citext.CICharField(max_length=250, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the tag"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "event tag",
                "verbose_name_plural": "event tags",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags to categorize and group related events",
                related_name="events",
                to="events.eventtag",
            ),
        ),
    ]
