# Generated by Django 5.2.1 on 2025-05-23 08:12

import common.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventtag_event_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', common.citext.CICharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the event group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'event group',
                'verbose_name_plural': 'event groups',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.AddField(
            model_name='event',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups linking related events', related_name='events', to='events.eventgroup'),
        ),
        migrations.DeleteModel(
            name='EventTag',
        ),
    ]
