# Generated by Django 5.2.1 on 2025-06-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_loadorganizationsfromkronostask"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
