# Generated by Django 5.2.1 on 2025-06-06 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_update_contact_language"),
        ("events", "0008_registration_created_at_registration_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="department",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="registration",
            name="designation",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="registration",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registrations",
                to="core.organization",
                verbose_name="Organization",
            ),
        ),
    ]
