# Generated by Django 5.2.1 on 2025-06-19 07:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_registration_department_registration_designation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="registration",
            name="is_funded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="registration",
            name="status",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.registrationstatus",
            ),
        ),
    ]
