# Generated by Django 5.2.1 on 2025-06-25 10:34

import ckeditor_uploader.fields
from django.db import migrations, models

import emails.validators


class Migration(migrations.Migration):
    dependencies = [
        (
            "events",
            "0010_alter_registration_date_alter_registration_is_funded_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="confirmation_content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True,
                default="",
                validators=[emails.validators.validate_placeholders],
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="confirmation_subject",
            field=models.CharField(
                blank=True,
                default="",
                max_length=900,
                validators=[emails.validators.validate_placeholders],
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="refuse_content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True,
                default="",
                validators=[emails.validators.validate_placeholders],
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="refuse_subject",
            field=models.CharField(
                blank=True,
                default="",
                max_length=900,
                validators=[emails.validators.validate_placeholders],
            ),
        ),
    ]
