# Generated by Django 5.2.1 on 2025-06-26 10:34

import ckeditor_uploader.fields
from django.db import migrations, models

import emails.validators


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_rename_status_registration_old_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="confirmation_content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True,
                default="",
                validators=[emails.validators.validate_placeholders],
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="confirmation_subject",
            field=models.CharField(
                blank=True,
                default="",
                max_length=900,
                validators=[emails.validators.validate_placeholders],
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="refuse_content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True,
                default="",
                validators=[emails.validators.validate_placeholders],
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="refuse_subject",
            field=models.CharField(
                blank=True,
                default="",
                max_length=900,
                validators=[emails.validators.validate_placeholders],
            ),
        ),
    ]
