# Generated by Django 5.2.1 on 2025-06-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0012_event_confirmation_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="designation",
            field=models.TextField(blank=True, default="", verbose_name="Job title"),
        ),
    ]
