# Generated by Django 5.2.1 on 2025-07-01 08:09

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    registration_model = apps.get_model("events", "Registration")
    pass_model = apps.get_model("events", "PriorityPass")
    db_alias = schema_editor.connection.alias

    # Move priority pass codes to the new model
    for obj in registration_model.objects.using(db_alias).all():
        if obj.priority_pass_code:
            priority_pass, created = pass_model.objects.using(db_alias).get_or_create(
                code=obj.priority_pass_code,
            )
        else:
            priority_pass = pass_model.objects.using(db_alias).create()

        obj.priority_pass = priority_pass
        obj.save()

        if priority_pass.registrations.distinct("contact").count() > 1:
            raise RuntimeError(
                f"Invalid priority pass code for contact: {obj.priority_pass_code}"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_alter_registration_designation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriorityPass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    django_extensions.db.fields.RandomCharField(
                        blank=True,
                        editable=False,
                        length=10,
                        unique=True,
                        uppercase=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="attach_priority_pass",
            field=models.BooleanField(
                default=False,
                help_text="Automatically attach priority pass to the accredited confirmation email",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="priority_pass",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registrations",
                to="events.prioritypass",
            ),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="registration",
            name="priority_pass_code",
        ),
    ]
