# Generated by Django 5.2.1 on 2025-07-01 05:39
import string

import django_extensions.db.fields
from django.db import migrations
from django.utils.crypto import get_random_string


def forwards_func(apps, schema_editor):
    klass = apps.get_model("events", "Registration")
    db_alias = schema_editor.connection.alias

    population = string.ascii_uppercase + string.digits

    # Add priority pass codes for any that don't have it yet
    for obj in klass.objects.using(db_alias).filter(priority_pass_code=""):
        obj.priority_pass_code = get_random_string(10, population)
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_contact_designation_and_more"),
        ("events", "0013_alter_registration_designation"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("contact", "event")},
        ),
        migrations.AlterField(
            model_name="registration",
            name="priority_pass_code",
            field=django_extensions.db.fields.RandomCharField(
                blank=True, editable=False, length=10, uppercase=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("contact", "event"), ("event", "priority_pass_code")},
        ),
    ]
