# Generated by Django 5.2.1 on 2025-07-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_prioritypass_remove_registration_priority_pass_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationrole",
            name="hide_for_nomination",
            field=models.BooleanField(
                default=False, help_text="Hide this role in the nomination form."
            ),
        ),
    ]
