# Generated by Django 5.2.1 on 2025-07-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_alter_registration_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attach_priority_pass",
            field=models.BooleanField(
                default=False,
                help_text="Automatically attach priority pass to the accredited confirmation email",
            ),
        ),
    ]
