# Generated by Django 5.2.1 on 2025-07-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0016_event_app_store_url_event_event_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="hide_for_nomination",
            field=models.BooleanField(
                default=False,
                help_text="Do not allow direct nominations for this event",
            ),
        ),
    ]
