# Generated by Django 5.2.1 on 2025-08-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0017_event_hide_for_nomination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Nominated", "Nominated"),
                    ("Accredited", "Accredited"),
                    ("Registered", "Registered"),
                    ("Revoked", "Revoked"),
                ],
                default="Nominated",
                max_length=20,
            ),
        ),
    ]
