# Generated by Django 5.2.1 on 2025-08-06 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0018_alter_registration_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ("-start_date",)},
        ),
        migrations.AlterModelOptions(
            name="eventgroup",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "event group",
                "verbose_name_plural": "event groups",
            },
        ),
        migrations.AlterModelOptions(
            name="registration",
            options={"ordering": ("-created_at",)},
        ),
    ]
