# Generated by Django 5.2.1 on 2025-09-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0019_alter_event_options_alter_eventgroup_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrationrole",
            options={"ordering": ("sort_order", "name")},
        ),
        migrations.AddField(
            model_name="registration",
            name="sort_order",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Override the role sort order for this registration.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registrationrole",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
