# Generated by Django 5.2.1 on 2025-09-25 08:41

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "events",
            "0020_alter_registrationrole_options_event_lop_doc_symbols_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="dsa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="term_exp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.CreateModel(
            name="DSA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("umoja_travel", models.CharField(blank=True, max_length=255)),
                ("bp", models.CharField(blank=True, max_length=255)),
                ("arrival_date", models.DateField(blank=True, null=True)),
                ("departure_date", models.DateField(blank=True, null=True)),
                ("cash_card", models.CharField(blank=True, max_length=255)),
                ("paid_dsa", models.BooleanField(default=False)),
                (
                    "boarding_pass",
                    encrypted_fields.fields.EncryptedJSONField(blank=True, null=True),
                ),
                (
                    "passport",
                    encrypted_fields.fields.EncryptedJSONField(blank=True, null=True),
                ),
                (
                    "signature",
                    encrypted_fields.fields.EncryptedJSONField(blank=True, null=True),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dsa",
                        to="events.registration",
                    ),
                ),
            ],
            options={
                "verbose_name": "DSA",
                "verbose_name_plural": "DSAs",
            },
        ),
    ]
