# Generated by Django 5.2.1 on 2025-10-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0021_event_dsa_event_term_exp_dsa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dsa",
            name="bp",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dsa",
            name="umoja_travel",
            field=models.CharField(max_length=255),
        ),
    ]
