# Generated by Django 5.2.1 on 2025-09-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0021_event_dsa_event_term_exp_dsa"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotatedRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "managed": False,
            },
        ),
    ]
