# Generated by Django 5.2.1 on 2025-10-01 09:31

import django_db_views.migration_functions
import django_db_views.operations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0022_annotatedregistration"),
    ]

    operations = [
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration(
                "SELECT registration.id                                                 AS id, \n               registration.id                                                 AS registration_id,\n               COALESCE(registration.organization_id, contact.organization_id) AS usable_organization_id\n        FROM events_registration AS registration\n                 LEFT JOIN core_contact AS contact ON registration.contact_id = contact.id",
                "events_annotatedregistration",
                engine="django.db.backends.postgresql",
            ),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration(
                "",
                "events_annotatedregistration",
                engine="django.db.backends.postgresql",
            ),
            atomic=False,
        ),
    ]
