# Generated by Django 5.2.1 on 2025-10-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0023_auto_20251001_0931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dsa",
            name="bp",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dsa",
            name="umoja_travel",
            field=models.CharField(max_length=255),
        ),
    ]
