# Generated by Django 5.2.1 on 2025-10-02 07:12

from django.db import migrations, models

import common.citext


def migrate_tags(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Registration = apps.get_model("events", "Registration")
    RegistrationTag = apps.get_model("events", "RegistrationTag")
    NewRegistrationTag = apps.get_model("events", "NewRegistrationTag")

    mapping = {}
    for old_tag in RegistrationTag.objects.using(db_alias).all():
        new_tag = NewRegistrationTag.objects.create(name=old_tag.name)
        mapping[old_tag] = new_tag

    for reg in Registration.objects.using(db_alias).all().prefetch_related("tags"):
        for tag in reg.tags.all():
            reg.new_tags.add(mapping.get(tag))


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0024_alter_dsa_bp_alter_dsa_umoja_travel"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewRegistrationTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", common.citext.CICharField(max_length=250, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="registration",
            name="new_tags",
            field=models.ManyToManyField(blank=True, to="events.newregistrationtag"),
        ),
        migrations.RunPython(migrate_tags, migrations.RunPython.noop),
    ]
