# Generated by Django 5.2.1 on 2025-10-02 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0025_newregistrationtag_registration_new_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="tags",
        ),
        migrations.DeleteModel(
            name="RegistrationTag",
        ),
        migrations.RenameModel(
            old_name="NewRegistrationTag",
            new_name="RegistrationTag",
        ),
        migrations.RenameField(
            model_name="registration",
            old_name="new_tags",
            new_name="tags",
        ),
    ]
