# Generated by Django 5.2.1 on 2025-10-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0026_remove_registration_tags_delete_registrationtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationtag",
            name="protected",
            field=models.BooleanField(default=False),
        ),
    ]
