# Generated by Django 5.2.1 on 2025-10-06 07:12

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0027_registrationtag_protected"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(default="UTC"),
        ),
    ]
