# Generated by Django 5.2.1 on 2025-10-06 06:01

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0028_event_timezone.py"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="credentials",
            field=encrypted_fields.fields.EncryptedJSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="has_credentials",
            field=models.BooleanField(default=False),
        ),
    ]
