# Generated by Django 5.2.7 on 2025-11-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0029_registration_credentials_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="include_badge_back_side",
            field=models.BooleanField(
                default=True,
                help_text="Include badge back side on A6. Disable to print directly to A7.",
            ),
        ),
    ]
