services:
  app:
    restart: always
    build:
      context: .
      dockerfile: docker/app.docker
      args:
        UV_ARGS: "--group dev"
    command: ["./manage.py", "runserver", "0:8000"]
    volumes:
      - .:/app

  worker:
    build:
      context: .
      dockerfile: docker/app.docker
      args:
        UV_ARGS: "--group dev"

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.docker
    ports:
      # Map to expose the docker webserver to outside
      - 8080:80
