services:
  app:
    build:
      context: .
      dockerfile: docker/app.docker
      args:
        UV_ARGS: "--group dev"
    environment:
      - GUNICORN_CMD_ARGS=--workers=2 --threads=2

  worker:
    build:
      context: .
      dockerfile: docker/app.docker
      args:
        UV_ARGS: "--group dev"

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.docker
    environment:
      - NGINX_WORKER_PROCESSES=2
    ports:
      - 8080:80
