services:
  app:
    restart: always
    build:
      context: .
      dockerfile: docker/app.dev.docker
    volumes:
      - .:/app

  worker:
    build:
      context: .
      dockerfile: docker/app.dev.docker

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.docker
    ports:
      # Map to expose the docker webserver to outside
      - 8080:80
