# Generated by Django 4.2.11 on 2024-04-12 08:44

import common.array_field
import common.citext
import common.model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_citext"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=30)),
                ("honorific", models.CharField(blank=True, default="", max_length=30)),
                ("respectful", models.CharField(blank=True, default="", max_length=30)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=250)),
                ("designation", models.TextField(blank=True, default="")),
                ("department", models.TextField(blank=True, default="")),
                ("affiliation", models.TextField(blank=True, default="")),
                (
                    "primary_lang",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="primary language",
                    ),
                ),
                (
                    "second_lang",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="second language",
                    ),
                ),
                (
                    "third_lang",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="third language",
                    ),
                ),
                (
                    "phones",
                    common.array_field.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "mobiles",
                    common.array_field.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "faxes",
                    common.array_field.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "emails",
                    common.array_field.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "email_ccs",
                    common.array_field.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_in_mailing_list", models.BooleanField(blank=True, default=False)),
                (
                    "is_use_organization_address",
                    models.BooleanField(blank=True, default=False),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, default="", max_length=250)),
                ("state", models.CharField(blank=True, default="", max_length=250)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("focal_point", models.BooleanField(blank=True, default=False)),
                (
                    "org_head",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="head of organization"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_id",
                    common.model.KronosId(
                        blank=True,
                        editable=False,
                        help_text="Unique Kronos ID. Will not be available if record was not imported from Kronos.",
                        max_length=24,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "code",
                    common.citext.CICharField(
                        max_length=2, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name_plural": "countries",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_id",
                    common.model.KronosId(
                        blank=True,
                        editable=False,
                        help_text="Unique Kronos ID. Will not be available if record was not imported from Kronos.",
                        max_length=24,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.TextField()),
                ("acronym", models.CharField(blank=True, max_length=30)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.country",
                    ),
                ),
                (
                    "government",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.country",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "country__name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationType",
            fields=[
                (
                    "organization_type_id",
                    common.model.KronosId(
                        blank=True,
                        editable=False,
                        help_text="Unique Kronos ID. Will not be available if record was not imported from Kronos.",
                        max_length=24,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    common.citext.CICharField(
                        max_length=250, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ResolveConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=30)),
                ("honorific", models.CharField(blank=True, default="", max_length=30)),
                ("respectful", models.CharField(blank=True, default="", max_length=30)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=250)),
                ("designation", models.TextField(blank=True, default="")),
                ("department", models.TextField(blank=True, default="")),
                ("affiliation", models.TextField(blank=True, default="")),
                (
                    "primary_lang",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="primary language",
                    ),
                ),
                (
                    "second_lang",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="second language",
                    ),
                ),
                (
                    "third_lang",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="third language",
                    ),
                ),
                (
                    "phones",
                    common.array_field.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "mobiles",
                    common.array_field.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "faxes",
                    common.array_field.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "emails",
                    common.array_field.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "email_ccs",
                    common.array_field.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_in_mailing_list", models.BooleanField(blank=True, default=False)),
                (
                    "is_use_organization_address",
                    models.BooleanField(blank=True, default=False),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, default="", max_length=250)),
                ("state", models.CharField(blank=True, default="", max_length=250)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("focal_point", models.BooleanField(blank=True, default=False)),
                (
                    "org_head",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="head of organization"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.country",
                    ),
                ),
                (
                    "existing_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicting_contacts",
                        to="core.contact",
                    ),
                ),
                (
                    "main_contact",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"main_contact": None},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secondary_contacts",
                        to="core.resolveconflict",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conflicting_contacts",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResolveAllConflictsTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="description"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="created on"),
                ),
                (
                    "started_on",
                    models.DateTimeField(null=True, verbose_name="started on"),
                ),
                (
                    "completed_on",
                    models.DateTimeField(null=True, verbose_name="completed on"),
                ),
                (
                    "progress",
                    models.IntegerField(blank=True, null=True, verbose_name="progress"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("RECEIVED", "RECEIVED"),
                            ("STARTED", "STARTED"),
                            ("PROGESS", "PROGESS"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILURE", "FAILURE"),
                            ("REVOKED", "REVOKED"),
                            ("REJECTED", "REJECTED"),
                            ("RETRY", "RETRY"),
                            ("IGNORED", "IGNORED"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=128,
                        verbose_name="status",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(blank=True, max_length=128, verbose_name="job id"),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "UNKNOWN"),
                            ("SYNC", "SYNC"),
                            ("ASYNC", "ASYNC"),
                        ],
                        db_index=True,
                        default="UNKNOWN",
                        max_length=128,
                        verbose_name="mode",
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="failure reason"
                    ),
                ),
                ("log_text", models.TextField(blank=True, verbose_name="log text")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("keep_old_data", "Keep old data"),
                            ("save_incoming_data", "Save incoming data"),
                        ],
                        max_length=60,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_on",
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="organization_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.organizationtype"
            ),
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.contact",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.contactgroup",
                    ),
                ),
            ],
            options={
                "unique_together": {("group", "contact")},
            },
        ),
        migrations.AddField(
            model_name="contactgroup",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="groups",
                through="core.GroupMembership",
                to="core.contact",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.country",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="main_contact",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"main_contact": None},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secondary_contacts",
                to="core.contact",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts",
                to="core.organization",
            ),
        ),
    ]
