# Generated by Django 4.2 on 2023-04-26 08:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_id", models.CharField(max_length=250, unique=True)),
                ("name", models.CharField(max_length=250)),
                ("acronym", models.CharField(blank=True, max_length=30)),
                ("organization_type_id", models.CharField(max_length=250)),
                ("organization_type", models.CharField(max_length=250)),
                ("government", models.CharField(blank=True, max_length=30)),
                ("government_name", models.CharField(blank=True, max_length=250)),
                ("country", models.CharField(blank=True, max_length=30)),
                ("country_name", models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_id", models.CharField(max_length=250, unique=True)),
                ("title", models.CharField(blank=True, max_length=30)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=250)),
                (
                    "designation",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                (
                    "affiliation",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                (
                    "phones",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, size=None
                    ),
                ),
                (
                    "mobiles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, size=None
                    ),
                ),
                (
                    "faxes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, size=None
                    ),
                ),
                (
                    "emails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, size=None
                    ),
                ),
                (
                    "email_ccs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, size=None
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_in_mailing_list", models.BooleanField()),
                ("is_use_organization_address", models.BooleanField()),
                ("address", models.CharField(blank=True, default="", max_length=250)),
                ("city", models.CharField(blank=True, default="", max_length=250)),
                ("state", models.CharField(blank=True, default="", max_length=250)),
                ("country", models.CharField(blank=True, default="", max_length=250)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistrationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=100)),
                ("status", models.IntegerField()),
                ("date", models.DateTimeField()),
                ("is_funded", models.BooleanField()),
                ("role", models.IntegerField(null=True)),
                ("priority_pass_code", models.CharField(blank=True, max_length=150)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, size=None
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.record"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "registration statuses",
            },
        ),
    ]
