# Generated by Django 4.2.11 on 2024-04-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResolveAllConflictsTask",
        ),
    ]
