# Generated by Django 4.2 on 2023-05-03 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_organization_record_registrationstatus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ["name"]},
        ),
    ]
