# Generated by Django 4.2.11 on 2024-04-19 13:04

import common.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_delete_resolveallconflictstask"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="official_name",
            field=common.citext.CICharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=common.citext.CICharField(blank=True, max_length=255, null=True),
        ),
    ]
