# Generated by Django 4.2.11 on 2024-05-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20240429_1104"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactgroup",
            options={"ordering": ("name",)},
        ),
    ]
