# Generated by Django 4.2.11 on 2024-04-22 05:53

import common.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_country_official_name_alter_country_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationtype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationtype",
            name="title",
            field=common.citext.CICharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="organizationtype",
            name="name",
            field=common.citext.CICharField(
                max_length=50, primary_key=True, serialize=False
            ),
        ),
    ]
