# Generated by Django 4.2 on 2023-05-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_organization_options_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="contacts",
            field=models.ManyToManyField(null=True, to="core.record"),
        ),
    ]
