# Generated by Django 4.2 on 2023-05-24 10:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_organization_options_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="focal_point",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="record",
            name="honorific",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="record",
            name="org_head",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Head of organization"
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="primary_lang",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Primary language"
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="respectful",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="record",
            name="second_lang",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Second language"
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="third_lang",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Third language"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="record",
            name="contact_id",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="record",
            name="email_ccs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="faxes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="is_in_mailing_list",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="record",
            name="is_use_organization_address",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="record",
            name="mobiles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="phones",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
    ]
