# Generated by Django 4.2.11 on 2024-06-03 06:13
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_importlegacycontactstask"),
    ]

    operations = [UnaccentExtension()]
