# Generated by Django 4.2.11 on 2024-04-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_organizationtype_description_organizationtype_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizationtype",
            options={"ordering": ("title",)},
        ),
        migrations.RenameField(
            model_name="organizationtype",
            old_name="name",
            new_name="acronym",
        ),
    ]
