# Generated by Django 5.2.1 on 2025-05-14 11:11

from django.db import migrations, models

import common.citext


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_unacent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactgroup",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=common.citext.CICharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="country",
            name="official_name",
            field=common.citext.CICharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organizationtype",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organizationtype",
            name="title",
            field=common.citext.CICharField(blank=True, default="", max_length=250),
            preserve_default=False,
        ),
    ]
