# Generated by Django 4.2.11 on 2024-04-22 07:21

import common.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_organizationtype_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="focal_point",
        ),
        migrations.RemoveField(
            model_name="resolveconflict",
            name="focal_point",
        ),
        migrations.AddField(
            model_name="contactgroup",
            name="predefined",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="contactgroup",
            name="name",
            field=common.citext.CICharField(max_length=255, unique=True),
        ),
    ]
