# Generated by Django 4.2.11 on 2024-04-23 11:55

import common.array_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_contact_focal_point_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="contact_id",
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_ids",
            field=common.array_field.ArrayField(
                base_field=models.TextField(),
                blank=True,
                editable=False,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="focal_point_ids",
            field=common.array_field.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                editable=False,
                null=True,
                size=None,
            ),
        ),
    ]
