# Generated by Django 5.2.1 on 2025-05-21 12:04

import common.array_field
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contactgroup_description_alter_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='organization_primary_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization_secondary_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='emails',
            field=common.array_field.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='organization',
            name='include_in_invitation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='importlegacycontactstask',
            name='json_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media/', location=pathlib.PurePosixPath('/Users/sorinstelian/edw/contactdb/.fs/protected_media')), upload_to='import_legacy_contact_files/'),
        ),
    ]
