# Generated by Django 5.2.1 on 2025-05-21 10:31

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contactgroup_description_alter_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='include_in_invitation',
            field=models.BooleanField(default=False),
        ),
    ]
