# Generated by Django 5.2.1 on 2025-05-22 12:24

from django.db import migrations, models

import common.array_field
import common.citext


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_contact_is_organization_and_more"),
    ]

    operations = [
        # Need to drop the views that used these fields otherwise we cannot alter them;
        # They'll be recreated in the next migration
        migrations.RunSQL(
            "DROP VIEW IF EXISTS core_possibleduplicate",
        ),
        migrations.RunSQL(
            "DROP VIEW IF EXISTS core_possibleduplicatecontact",
        ),
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="organization",
            name="city",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="organization",
            name="email_ccs",
            field=common.array_field.ArrayField(
                base_field=common.citext.CIEmailField(max_length=254),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="emails",
            field=common.array_field.ArrayField(
                base_field=common.citext.CIEmailField(max_length=254),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="faxes",
            field=common.array_field.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="phones",
            field=common.array_field.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="organization",
            name="state",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="organization",
            name="websites",
            field=common.array_field.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email_ccs",
            field=common.array_field.ArrayField(
                base_field=common.citext.CIEmailField(max_length=254),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="emails",
            field=common.array_field.ArrayField(
                base_field=common.citext.CIEmailField(max_length=254),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="resolveconflict",
            name="email_ccs",
            field=common.array_field.ArrayField(
                base_field=common.citext.CIEmailField(max_length=254),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="resolveconflict",
            name="emails",
            field=common.array_field.ArrayField(
                base_field=common.citext.CIEmailField(max_length=254),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
