# Generated by Django 4.2 on 2023-05-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_loadkronoseventstask"),
    ]

    operations = [
        migrations.CreateModel(
            name="KronosEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=150, unique=True)),
                ("code", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("venue_country", models.CharField(max_length=50)),
                ("venue_city", models.CharField(max_length=150)),
                ("dates", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "kronos events",
            },
        ),
    ]
