# Generated by Django 5.2.1 on 2025-05-22 10:11


import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_contact_is_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="is_organization",
            field=models.BooleanField(
                default=False,
                help_text="Is this contact just a placeholder for an organization email address?",
            ),
        ),
        migrations.CreateModel(
            name="ContactOrganizationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.TextField(blank=True, default="")),
                ("department", models.TextField(blank=True, default="")),
                ("affiliation", models.TextField(blank=True, default="")),
                (
                    "org_head",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="head of organization"
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_history",
                        to="core.contact",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contact organization histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
