# Generated by Django 5.2.1 on 2025-05-22 08:48

import common.array_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_contact_is_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="organization",
            name="city",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="organization",
            name="faxes",
            field=common.array_field.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="phones",
            field=common.array_field.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="organization",
            name="state",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="organization",
            name="websites",
            field=common.array_field.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
    ]
