# Generated by Django 5.2.1 on 2025-05-22 11:43

from django.db import migrations

import common.array_field
import common.citext


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_organization_address_organization_city_and_more"),
    ]

    operations = [
        # Need to drop the views that used these fields otherwise we cannot alter them;
        # They'll be recreated in the next migration
        migrations.RunSQL(
            "DROP VIEW IF EXISTS core_possibleduplicate",
        ),
        migrations.RunSQL(
            "DROP VIEW IF EXISTS core_possibleduplicatecontact",
        ),
        migrations.AlterField(
            model_name="contact",
            name="email_ccs",
            field=common.array_field.ArrayField(
                base_field=common.citext.CIEmailField(max_length=254),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="emails",
            field=common.array_field.ArrayField(
                base_field=common.citext.CIEmailField(max_length=254),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="resolveconflict",
            name="email_ccs",
            field=common.array_field.ArrayField(
                base_field=common.citext.CIEmailField(max_length=254),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="resolveconflict",
            name="emails",
            field=common.array_field.ArrayField(
                base_field=common.citext.CIEmailField(max_length=254),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
