# Generated by Django 4.2 on 2023-05-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_kronosevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kronosevent",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="kronosevent",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
