# Generated by Django 5.2.1 on 2025-05-23 07:03

import common.array_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auto_20250522_1224"),
    ]

    operations = [
        migrations.CreateModel(
            name="PossibleDuplicateContactRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PossibleDuplicateOrganization",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                (
                    "duplicate_fields",
                    common.array_field.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                (
                    "duplicate_values",
                    common.array_field.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                (
                    "organization_ids",
                    common.array_field.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                ("is_dismissed", models.BooleanField(default=False)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PossibleDuplicateOrganizationRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DismissedDuplicateOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_ids",
                    common.array_field.ArrayField(
                        base_field=models.IntegerField(), size=None, unique=True
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="DismissedDuplicate",
            new_name="DismissedDuplicateContact",
        ),
        migrations.DeleteModel(
            name="PossibleDuplicate",
        ),
    ]
