# Generated by Django 4.2 on 2023-06-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_loadkronosparticipantstask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationstatus",
            name="event_id",
        ),
        migrations.AddField(
            model_name="registrationstatus",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.kronosevent",
            ),
            preserve_default=False,
        ),
    ]
