# Generated by Django 5.2.1 on 2025-05-23 14:31

import pathlib

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_auto_20250523_0703"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importlegacycontactstask",
            name="json_file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/protected_media/",
                    location=pathlib.PurePosixPath(
                        "/home/mboboc/contactdb/.fs/protected_media"
                    ),
                ),
                upload_to="import_legacy_contact_files/",
            ),
        ),
    ]
