# Generated by Django 4.2.11 on 2024-04-25 06:26

import common.array_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20240424_1336"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="alt_names",
            field=common.array_field.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organizationtype",
            ),
        ),
    ]
