# Generated by Django 5.2.1 on 2025-05-26 08:38

import json
import logging
from pathlib import Path

from django.conf import settings
from django.core.management import call_command
from django.db import migrations

logger = logging.getLogger(__name__)


def load_region_subregion_country(apps, schema_editor):
    call_command("loaddata", "initial/region.json")
    call_command("loaddata", "initial/subregion.json")
    call_command("loaddata", "initial/country.json")


def load_region_subregion_country_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_region_subregion_and_more"),
    ]

    operations = [
        migrations.RunPython(
            load_region_subregion_country,
            reverse_code=load_region_subregion_country_backward,
        ),
    ]
