# Generated by Django 5.2.1 on 2025-05-26 08:38

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_region_subregion_and_more"),
    ]

    operations = []
