# Generated by Django 4.2.1 on 2023-06-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_temporarycontact_resolveallconflictstask"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="main_contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.record",
            ),
        ),
    ]
