# Generated by Django 5.2.1 on 2025-05-28 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_update_existing_countries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts",
                to="core.organization",
                verbose_name="Organization",
            ),
        ),
    ]
