# Generated by Django 4.2.1 on 2023-07-03 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_record_main_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="main_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.record",
            ),
        ),
    ]
