# Generated by Django 4.2.1 on 2023-07-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_record_main_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="emails",
            name="groups",
            field=models.ManyToManyField(null=True, to="core.group"),
        ),
    ]
