# Generated by Django 5.2.1 on 2025-05-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_contact_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="is_in_mailing_list",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="is_organization",
        ),
        migrations.RemoveField(
            model_name="resolveconflict",
            name="is_in_mailing_list",
        ),
        migrations.AlterField(
            model_name="contact",
            name="primary_lang",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E", "English"),
                    ("F", "French"),
                    ("S", "Spanish"),
                    ("A", "Arabic"),
                    ("C", "Chinese"),
                    ("R", "Russian"),
                ],
                default="",
                max_length=2,
                verbose_name="primary language",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="second_lang",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E", "English"),
                    ("F", "French"),
                    ("S", "Spanish"),
                    ("A", "Arabic"),
                    ("C", "Chinese"),
                    ("R", "Russian"),
                ],
                default="",
                max_length=2,
                verbose_name="second language",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="third_lang",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E", "English"),
                    ("F", "French"),
                    ("S", "Spanish"),
                    ("A", "Arabic"),
                    ("C", "Chinese"),
                    ("R", "Russian"),
                ],
                default="",
                max_length=2,
                verbose_name="third language",
            ),
        ),
        migrations.AlterField(
            model_name="resolveconflict",
            name="primary_lang",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E", "English"),
                    ("F", "French"),
                    ("S", "Spanish"),
                    ("A", "Arabic"),
                    ("C", "Chinese"),
                    ("R", "Russian"),
                ],
                default="",
                max_length=2,
                verbose_name="primary language",
            ),
        ),
        migrations.AlterField(
            model_name="resolveconflict",
            name="second_lang",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E", "English"),
                    ("F", "French"),
                    ("S", "Spanish"),
                    ("A", "Arabic"),
                    ("C", "Chinese"),
                    ("R", "Russian"),
                ],
                default="",
                max_length=2,
                verbose_name="second language",
            ),
        ),
        migrations.AlterField(
            model_name="resolveconflict",
            name="third_lang",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E", "English"),
                    ("F", "French"),
                    ("S", "Spanish"),
                    ("A", "Arabic"),
                    ("C", "Chinese"),
                    ("R", "Russian"),
                ],
                default="",
                max_length=2,
                verbose_name="third language",
            ),
        ),
    ]
