# Generated by Django 5.2.1 on 2025-05-29 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_contact_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="organization_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizations",
                to="core.organizationtype",
            ),
        ),
    ]
