# Generated by Django 4.2.1 on 2023-07-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_emails_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20)),
            ],
        ),
    ]
