# Generated by Django 5.2.1 on 2025-05-29 16:20

import common.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_organization_organization_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importlegacycontactstask",
            name="json_file",
            field=models.FileField(
                storage=common.model.get_protected_storage,
                upload_to="import_legacy_contact_files/",
            ),
        ),
    ]
