# Generated by Django 5.2.1 on 2025-05-29 16:41

from django.db import migrations, models

import common.model


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_remove_contact_is_in_mailing_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importlegacycontactstask",
            name="json_file",
            field=models.FileField(
                storage=common.model.get_protected_storage,
                upload_to="import_legacy_contact_files/",
            ),
        ),
    ]
