# Generated by Django 4.2.1 on 2023-07-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_emailtag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sendmailtask",
            name="message",
        ),
        migrations.RemoveField(
            model_name="sendmailtask",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="sendmailtask",
            name="subject",
        ),
        migrations.AddField(
            model_name="emails",
            name="send_personalised_emails",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sendmailtask",
            name="email",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.emails",
            ),
        ),
        migrations.AlterField(
            model_name="emails",
            name="groups",
            field=models.ManyToManyField(to="core.group"),
        ),
    ]
