# Generated by Django 5.2.1 on 2025-05-30 09:25

from django.db import migrations

from events.parsers import KronosParticipantsParser


def update_contact_language(apps, schema_editor):
    Contact = apps.get_model("core", "Contact")
    contacts = Contact.objects.all()

    for contact in contacts:
        langs = KronosParticipantsParser.get_languages(contact.notes)

        for field, value in langs.items():
            setattr(contact, field, value)
        contact.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_importlegacycontactstask_json_file"),
    ]

    operations = [
        migrations.RunPython(
            update_contact_language,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
