# Generated by Django 4.2.1 on 2023-07-17 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_remove_sendmailtask_message_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emails",
            old_name="title",
            new_name="subject",
        ),
    ]
