# Generated by Django 4.2.1 on 2023-07-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_rename_title_emails_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="kronosevent",
            name="group",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.group",
            ),
        ),
        migrations.AddField(
            model_name="loadkronosparticipantstask",
            name="create_groups",
            field=models.BooleanField(default=False),
        ),
    ]
