# Generated by Django 4.2.1 on 2023-07-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_kronosevent_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("html_content", models.TextField()),
            ],
        ),
    ]
