# Generated by Django 5.2.1 on 2025-06-21 10:02

import common.array_field
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_auto_20250619_1245"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportContactPhotosTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="description"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="created on"),
                ),
                (
                    "started_on",
                    models.DateTimeField(null=True, verbose_name="started on"),
                ),
                (
                    "completed_on",
                    models.DateTimeField(null=True, verbose_name="completed on"),
                ),
                (
                    "progress",
                    models.IntegerField(blank=True, null=True, verbose_name="progress"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("RECEIVED", "RECEIVED"),
                            ("STARTED", "STARTED"),
                            ("PROGESS", "PROGESS"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILURE", "FAILURE"),
                            ("REVOKED", "REVOKED"),
                            ("REJECTED", "REJECTED"),
                            ("RETRY", "RETRY"),
                            ("IGNORED", "IGNORED"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=128,
                        verbose_name="status",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(blank=True, max_length=128, verbose_name="job id"),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "UNKNOWN"),
                            ("SYNC", "SYNC"),
                            ("ASYNC", "ASYNC"),
                        ],
                        db_index=True,
                        default="UNKNOWN",
                        max_length=128,
                        verbose_name="mode",
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="failure reason"
                    ),
                ),
                ("log_text", models.TextField(blank=True, verbose_name="log text")),
                (
                    "contact_ids",
                    common.array_field.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        help_text="Specific Contact ids (internal, not Kronos ids) to process. Null value means all contacts are processed.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "overwrite_existing",
                    models.BooleanField(
                        default=True, help_text="Overwrite any existing photos."
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "get_latest_by": "created_on",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Contact photo; initially imported from Kronos",
                null=True,
                upload_to="contact_photos/",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="photo_access_uuid",
            field=models.UUIDField(default=None, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("photo_access_uuid__isnull", False)),
                fields=("photo_access_uuid",),
                name="unique_photo_access_uuid_not_null",
            ),
        ),
        migrations.AddField(
            model_name="importcontactphotostask",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
