# Generated by Django 5.2.1 on 2025-06-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_contact_photo_importcontactphotostask"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="photo_access_uuid",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("photo_access_uuid__isnull", False)),
                fields=("photo_access_uuid",),
                name="unique_photo_access_uuid_not_null",
            ),
        ),
    ]
