# Generated by Django 5.2.1 on 2025-06-21 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_importcontactphotostask_contact_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="photo_access_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
