# Generated by Django 4.2.1 on 2023-08-07 08:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_emailfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emails",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="html_content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
