# Generated by Django 5.2.1 on 2025-06-24 12:35

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_contact_photo_access_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="credentials",
            field=encrypted_fields.fields.EncryptedJSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="has_credentials",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contact",
            name="nationality",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="needs_visa_letter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contact",
            name="passport",
            field=encrypted_fields.fields.EncryptedJSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="passport_date_of_expiry",
            field=encrypted_fields.fields.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="passport_date_of_issue",
            field=encrypted_fields.fields.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="passport_number",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="resolveconflict",
            name="credentials",
            field=encrypted_fields.fields.EncryptedJSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resolveconflict",
            name="has_credentials",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resolveconflict",
            name="nationality",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="resolveconflict",
            name="needs_visa_letter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resolveconflict",
            name="passport",
            field=encrypted_fields.fields.EncryptedJSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resolveconflict",
            name="passport_date_of_expiry",
            field=encrypted_fields.fields.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resolveconflict",
            name="passport_date_of_issue",
            field=encrypted_fields.fields.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resolveconflict",
            name="passport_number",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=20, null=True
            ),
        ),
    ]
