# Generated by Django 5.2.1 on 2025-06-27 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_contact_designation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="affiliation",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="respectful",
        ),
        migrations.RemoveField(
            model_name="resolveconflict",
            name="affiliation",
        ),
        migrations.RemoveField(
            model_name="resolveconflict",
            name="respectful",
        ),
    ]
