# Generated by Django 5.2.1 on 2025-07-07 13:25

from django.db import migrations

from common.parsing import title_map
from core.models import BaseContact


def migrate_title(apps, schema_editor):
    Contact = apps.get_model("core", "Contact")

    for contact in Contact.objects.all():
        if contact.title:
            contact_title = title_map.get(contact.title, contact.title)
            contact.title_new = (
                contact_title if contact_title in BaseContact.Title.values else ""
            )

            contact.save(update_fields=["title_new"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_contact_title_new_resolveconflict_title_new"),
    ]

    operations = [
        migrations.RunPython(
            migrate_title,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
