# Generated by Django 5.2.1 on 2025-07-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_contact_title_new_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="title_localized",
            field=models.CharField(
                blank=True,
                help_text="Localized title in French or Spanish.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="resolveconflict",
            name="title_localized",
            field=models.CharField(
                blank=True,
                help_text="Localized title in French or Spanish.",
                max_length=30,
            ),
        ),
    ]
