# Generated by Django 5.2.1 on 2025-07-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_populate_localized_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mr.", "Mr."),
                    ("Ms.", "Ms."),
                    ("H.E. Mr.", "H.E. Mr."),
                    ("H.E. Ms.", "H.E. Ms."),
                    ("Hon. Mr.", "Hon. Mr."),
                    ("Hon. Ms.", "Hon. Ms."),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="title_localized",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mr.", "Mr."),
                    ("Ms.", "Ms."),
                    ("H.E. Mr.", "H.E. Mr."),
                    ("H.E. Ms.", "H.E. Ms."),
                    ("Hon. Mr.", "Hon. Mr."),
                    ("Hon. Ms.", "Hon. Ms."),
                    ("M.", "M."),
                    ("Mme.", "Mme."),
                    ("H.E. M.", "H.E. M."),
                    ("H.E. Mme.", "H.E. Mme."),
                    ("Hon. M.", "Hon. M."),
                    ("Hon. Mme.", "Hon. Mme."),
                    ("Sr.", "Sr."),
                    ("Sra.", "Sra."),
                    ("H.E. Sr.", "H.E. Sr."),
                    ("H.E. Sra.", "H.E. Sra."),
                    ("Hon. Sr.", "Hon. Sr."),
                    ("Hon. Sra.", "Hon. Sra."),
                ],
                help_text="Localized title in French or Spanish.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="resolveconflict",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mr.", "Mr."),
                    ("Ms.", "Ms."),
                    ("H.E. Mr.", "H.E. Mr."),
                    ("H.E. Ms.", "H.E. Ms."),
                    ("Hon. Mr.", "Hon. Mr."),
                    ("Hon. Ms.", "Hon. Ms."),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="resolveconflict",
            name="title_localized",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mr.", "Mr."),
                    ("Ms.", "Ms."),
                    ("H.E. Mr.", "H.E. Mr."),
                    ("H.E. Ms.", "H.E. Ms."),
                    ("Hon. Mr.", "Hon. Mr."),
                    ("Hon. Ms.", "Hon. Ms."),
                    ("M.", "M."),
                    ("Mme.", "Mme."),
                    ("H.E. M.", "H.E. M."),
                    ("H.E. Mme.", "H.E. Mme."),
                    ("Hon. M.", "Hon. M."),
                    ("Hon. Mme.", "Hon. Mme."),
                    ("Sr.", "Sr."),
                    ("Sra.", "Sra."),
                    ("H.E. Sr.", "H.E. Sr."),
                    ("H.E. Sra.", "H.E. Sra."),
                    ("Hon. Sr.", "Hon. Sr."),
                    ("Hon. Sra.", "Hon. Sra."),
                ],
                help_text="Localized title in French or Spanish.",
                max_length=30,
            ),
        ),
    ]
