# Generated by Django 5.2.1 on 2025-07-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_alter_contact_title_alter_contact_title_localized_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Other", "Other"),
                    ("Choose not to disclose", "Choose not to disclose"),
                ],
                help_text="Contact gender.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="resolveconflict",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Other", "Other"),
                    ("Choose not to disclose", "Choose not to disclose"),
                ],
                help_text="Contact gender.",
                max_length=30,
            ),
        ),
    ]
