# Generated by Django 5.2.1 on 2025-07-21 06:08

from django.db import migrations, models

import common.array_field


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_contact_gender_resolveconflict_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importcontactphotostask",
            name="contact_ids",
            field=common.array_field.ArrayField(
                base_field=models.BigIntegerField(),
                blank=True,
                help_text="Specific Contact ids (internal, not Kronos ids) to process. Null value means all contacts are processed.",
                null=True,
                size=None,
            ),
        ),
    ]
