# Generated by Django 5.2.1 on 2025-08-27 06:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_photos_uuid_data_migation"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contact",
            name="unique_photo_access_uuid_not_null",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="photo_access_uuid",
        ),
    ]
