# Generated by Django 5.2.1 on 2025-08-27 12:14

import django.db.models.deletion
from django.db import migrations, models

import common.citext
import common.model


def migrate_org_types(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Organization = apps.get_model("core", "Organization")
    OrganizationType = apps.get_model("core", "OrganizationType")
    OrganizationTypeNew = apps.get_model("core", "OrganizationTypeNew")

    mapping = {}
    for org_old in OrganizationType.objects.using(db_alias).all():
        org_new = OrganizationTypeNew.objects.create(
            organization_type_id=org_old.organization_type_id,
            acronym=org_old.acronym,
            title=org_old.title,
            description=org_old.description,
        )
        mapping[org_old] = org_new

    for org in Organization.objects.using(db_alias).all():
        org.organization_type_new = mapping.get(org.organization_type)
        org.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_photos_uuid_data_migation"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationTypeNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_type_id",
                    common.model.KronosId(
                        blank=True,
                        editable=False,
                        help_text="Unique Kronos ID. Will not be available if record was not imported from Kronos.",
                        max_length=24,
                        null=True,
                        unique=True,
                        verbose_name="Kronos ID",
                    ),
                ),
                ("acronym", common.citext.CICharField(max_length=50, unique=True)),
                ("title", common.citext.CICharField(blank=True, max_length=250)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="organization_type_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizations_new",
                to="core.organizationtypenew",
            ),
        ),
        migrations.RunPython(migrate_org_types, migrations.RunPython.noop),
    ]
