# Generated by Django 5.2.1 on 2025-08-27 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_organizationtypenew_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="organization", name="organization_type"),
        migrations.RenameField(
            model_name="organization",
            old_name="organization_type_new",
            new_name="organization_type",
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizations",
                to="core.organizationtypenew",
            ),
        ),
    ]
