# Generated by Django 5.2.1 on 2025-08-27 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_auto_20250827_1222"),
        ("emails", "0012_auto_20250827_1225"),
    ]

    operations = [
        migrations.DeleteModel(name="organizationtype"),
        migrations.RenameModel(
            old_name="organizationtypenew", new_name="organizationtype"
        ),
    ]
