# Generated by Django 5.2.1 on 2025-08-27 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_auto_20250827_1228"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contact",
            name="unique_photo_access_uuid_not_null",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="photo_access_uuid",
        ),
    ]
