# Generated by Django 5.2.1 on 2025-08-28 09:13

from django.db import migrations

import common.citext


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_remove_contact_unique_photo_access_uuid_not_null_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationtype",
            name="badge_title",
            field=common.citext.CICharField(
                blank=True,
                help_text="Used on badges instead of the title.",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="organizationtype",
            name="statistics_title",
            field=common.citext.CICharField(
                blank=True,
                help_text="Used for event statistics instead of the title.",
                max_length=250,
            ),
        ),
    ]
