# Generated by Django 5.2.1 on 2025-09-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_organizationtype_badge_color_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ("sort_order", "name", "country__name")},
        ),
        migrations.AlterModelOptions(
            name="organizationtype",
            options={"ordering": ("sort_order", "title")},
        ),
        migrations.AddField(
            model_name="organization",
            name="sort_order",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="organizationtype",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
