# Generated by Django 5.2.1 on 2025-09-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_alter_organization_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subregion",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelOptions(
            name="region",
            options={
                "ordering": ("sort_order", "name"),
                "verbose_name_plural": "regions",
            },
        ),
        migrations.AlterModelOptions(
            name="subregion",
            options={
                "ordering": ("sort_order", "name"),
                "verbose_name_plural": "subregions",
            },
        ),
    ]
