# Generated by Django 5.2.1 on 2025-10-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_alter_region_options_alter_subregion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationtype",
            name="protected",
            field=models.BooleanField(default=False),
        ),
    ]
