# Generated by Django 4.2 on 2023-04-27 11:50

import contactdb.citext
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_edit",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can edit contacts.",
                verbose_name="Edit contacts",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="can_import",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can import contacts.",
                verbose_name="Import contacts",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="can_send_mail",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can send emails to contacts.",
                verbose_name="Send emails",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="can_view",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether the user can view contacts.",
                verbose_name="View contacts",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=contactdb.citext.CIEmailField(
                help_text="You can use <a href=\"../password/\">this form</a> to change the password. It is recommended to use 'Forgot password' for account retrieval.",
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether the account can be used. It is recommended to disable an account instead of deleting.",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can access the admin page.",
                verbose_name="Staff",
            ),
        ),
    ]
