# Generated by Django 4.2.11 on 2024-04-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_groups_role_user_roles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "role", "verbose_name_plural": "roles"},
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="The roles this user has. A user will get all permissions granted to each of their roles.",
                related_name="user_set",
                related_query_name="user",
                to="accounts.role",
            ),
        ),
    ]
