<template>
  <q-stepper ref="stepper" v-model="step" color="primary" animated vertical>
    <q-step :name="1" title="Enable 2FA" :done="step > 1">
      <p>
        Two-factor authentication is not enabled for your account. Enable two-factor authentication for enhanced account
        security.
      </p>
      <q-btn color="primary" @click="initStep">Enable</q-btn>
    </q-step>
    <q-step :name="2" title="Configure Device" :done="step > 2">
      <p>
        To start using a token generator, please use your smartphone to scan the QR code below. For example, use Google
        Authenticator. Then, enter the token generated by the app.
      </p>
      <img v-if="step > 1" id="qr-code" :src="qrCodeUrl" alt="" class="q-my-md" />
      <q-input
        v-model="code"
        autofocus
        label="Code"
        mask="######"
        filled
        autocomplete="otp"
        :error="!!errors.token"
        :error-message="errors.token"
      />
      <q-btn color="primary" @click="completeStep">Confirm</q-btn>
    </q-step>
    <q-step :name="3" title="Generate Backup Tokens" :done="step > 3">
      <p>Backup tokens can be used when your primary device is not available. Each token can only be used once.</p>
      <q-btn color="primary" @click="generateBackupTokens">Generate tokens</q-btn>
    </q-step>
    <q-step :name="4" title="Save Backup Tokens" :done="step > 4">
      <p>Print these tokens and keep them somewhere safe.</p>
      <ul>
        <li v-for="token in backupTokens" :key="token">
          {{ token }}
        </li>
      </ul>
      <br />
      <p>
        <q-btn color="primary" @click="reloadStore">Done</q-btn>
      </p>
    </q-step>
    <q-inner-loading :showing="loading">
      <q-spinner-tail size="50px" color="primary" />
    </q-inner-loading>
  </q-stepper>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";
import { useUserStore } from "stores/userStore";
import { api, apiURL } from "boot/axios";
import useFormErrors from "src/composables/useFormErrors";

const userStore = useUserStore();

const { errors, setErrors } = useFormErrors();

const qrCodeUrl = `${apiURL}/account/two_factor/setup/qrcode/`;
const loading = ref(false);
const step = ref(1);
const code = ref("");
const backupTokens = ref<string[]>([]);

async function initStep() {
  const data = new FormData();
  data.append("two_factor_setup_view-current_step", "welcome");

  try {
    loading.value = true;
    await api.post("/account/two_factor/setup/", data);
    step.value += 1;
  } catch (e) {
    setErrors(e);
  } finally {
    loading.value = false;
  }
}
async function completeStep() {
  const data = new FormData();
  data.append("two_factor_setup_view-current_step", "generator");
  data.append("generator-token", code.value);

  try {
    loading.value = true;
    await api.post("/account/two_factor/setup/", data);
    step.value += 1;
  } catch (e) {
    setErrors(e);
  } finally {
    loading.value = false;
  }
}
async function generateBackupTokens() {
  try {
    loading.value = true;
    backupTokens.value = (await api.post("/account/two_factor/backup/tokens/")).data.tokens;
    step.value += 1;
  } catch (e) {
    setErrors(e);
  } finally {
    loading.value = false;
  }
}

async function reloadStore() {
  await userStore.fetchUser();
}

watch(code, async (newCode) => {
  if (newCode.length === 6) {
    await completeStep();
  }
});
</script>

<style scoped lang="scss"></style>
