concurrency: deployment

on:
  workflow_call:
    inputs:
      runner_label:
        description: "Runner label to deploy to"
        required: true
        type: string
jobs:
  deploy:
    runs-on:
      - self-hosted
      - ${{ inputs.runner_label }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Update compose.yml
        run: |
          cp compose.yml /home/contactdb/
      - name: Update services
        run: |
          cd /home/contactdb/
          sed -i "/^DOCKER_TAG=/c\DOCKER_TAG=$GITHUB_REF_NAME" .env
          docker compose pull
          docker compose up -d --remove-orphans
          docker compose top
